src/views/front.py
# -*- coding: utf-8 -*-
"""
    EauDouce.views.front
    ~~~~~~~~~~~~~~

    Foreground view.

    :copyright: (c) 2017 by Mr.tao.
    :license: MIT, see LICENSE for more details.
"""

import datetime
from urlparse import urljoin
from werkzeug.contrib.atom import AtomFeed
from flask import Blueprint, g, render_template, request, redirect, url_for, make_response, abort
from utils.tool import login_required, logger, BaiduActivePush

front_blueprint = Blueprint("front", __name__)

@front_blueprint.route("/")
def index():
    return render_template("front/blogIndex.html")

@front_blueprint.route('/blog/<int:bid>.html')
def blogShow(bid):
    data = g.api.blog_get_id(bid).get("data")
    if data:
        BaiduActivePushResult = False
        if g.plugins['BaiduActivePush']['enable'] in ("true", "True", True):
            BaiduActivePushResult = True if BaiduActivePush(request.url, original=True if data.get("sources") == "原创" else False).get("success_realtime") == 1 else False
        logger.sys.info("BaiduActivePushResult for id: %s, %s" %(bid, BaiduActivePushResult))
        return render_template("front/blogShow.html", blogId=bid, data=data, BaiduActivePushResult=BaiduActivePushResult)
    else:
        return abort(404)

@front_blueprint.route("/blog/write/")
@login_required
def blogWrite():
    return render_template("front/blogWrite.html")

@front_blueprint.route("/blog/edit/")
@login_required
def blogEdit():
    blogId = request.args.get("blogId")
    if blogId:
        data = g.api.blog_get_id(blogId).get("data")
        if data:
            if g.username == data.get("author") or g.username in g.api.user_get_admins().get("data"):
                return render_template("front/blogEdit.html", blogId=blogId, data=data)
        return abort(404)

@front_blueprint.route("/blog/resource/")
def blogResource():
    return render_template("front/blogResource.html")

@front_blueprint.route("/blog/search/")
def blogSearch():
    return render_template("front/blogSearch.html")

@front_blueprint.route("/user/<user>/")
def userHome(user=None):
    return render_template("front/userHome.html", user=user)

@front_blueprint.route("/user/ChangeAvater/")
@login_required
def userChangeAvater():
    return render_template("front/userChangeAvater2.html")
    return render_template("front/userChangeAvater.html")

@front_blueprint.route("/user/ChangePassword/")
@login_required
def userChangePassword():
    return render_template("front/userChangePassword.html")

@front_blueprint.route("/user/ChangeCover/")
@login_required
def userChangeCover():
    return render_template("front/userChangeCover.html")

@front_blueprint.route("/user/ChangeProfile/")
@login_required
def userChangeProfile():
    return render_template("front/userChangeProfile.html")

@front_blueprint.route("/robots.txt")
def robots():
    return """
User-agent: *
Disallow: 
    """

@front_blueprint.route("/sitemap.xml")
def sitemapxml():
    resp = make_response(render_template("public/sitemap.xml"))
    resp.headers["Content-Type"] = "application/xml"    
    return resp

@front_blueprint.route("/sitemap.html")
def sitemaphtml():
    return render_template("public/sitemap.html")

@front_blueprint.route("/feed/")
def feed():
    data = g.api.blog_get_all(limit=10).get("data")
    feed = AtomFeed(g.api.get_sys_config().get("data").get("site_feedname"), feed_url=request.url, url=request.url_root, subtitle="From the latest article in {}".format(request.url))
    for article in data:
        updated = article['update_time'][:10] if article['update_time'] else article['create_time'][:10]
        feed.add(article['title'], unicode(article['content']),
                 content_type='html',
                 author=article['author'],
                 id=article['id'],
                 url=urljoin(request.url_root, url_for(".blogShow", bid=article['id'])),
                 updated=datetime.datetime.strptime(updated, "%Y-%m-%d"),
                 published=datetime.datetime.strptime(article['create_time'][:10], "%Y-%m-%d"))
    return feed.get_response()

@front_blueprint.route("/thirds/StaticUpload/")
def thirdPluginStaticUpload():
    return render_template("admin/thirdPluginStaticUpload.html")

src/views/upload.py
# -*- coding: utf-8 -*-
"""
    EauDouce.views.upload
    ~~~~~~~~~~~~~~

    File upload view.

    :copyright: (c) 2017 by Mr.tao.
    :license: MIT, see LICENSE for more details.
"""

import os, base64
from utils.tool import logger, gen_rnd_filename, UploadImage2Upyun
from flask import Blueprint, request, Response, url_for, redirect, g, jsonify
from werkzeug import secure_filename
from config import PLUGINS
from thirds.binbase64 import base64str

upload_blueprint = Blueprint("upload", __name__)
#文件上传文件夹, 相对于项目根目录, 请勿改动static/部分
IMAGE_FOLDER     = 'static/img/upload/'
UPLOAD_FOLDER    = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), IMAGE_FOLDER)

#文件名合法性验证
allowed_file = lambda filename: '.' in filename and filename.rsplit('.', 1)[1] in set(['png', 'jpg', 'jpeg', 'gif'])

#对博客图片上传进行响应
@upload_blueprint.route("/BlogImage/", methods=["POST",])
def UploadBlogImage():
    editorType = request.args.get("editorType", "wangEditor")
    logger.sys.debug(request.files)
    f = request.files.get("WriteBlogImage") or request.files.get("editormd-image-file")
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_rnd_filename() + "." + f.filename.split('.')[-1]) #随机命名
        if PLUGINS['UpYunStorage']['enable'] in ('true', 'True', True):
            imgUrl = "/EauDouce/blog/" + filename
            upres  = UploadImage2Upyun(imgUrl, f.stream.read())
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.sys.info("Blog to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            if not os.path.exists(UPLOAD_FOLDER): os.makedirs(UPLOAD_FOLDER)
            f.save(os.path.join(UPLOAD_FOLDER, filename))
            imgUrl = request.url_root + IMAGE_FOLDER + filename
            logger.sys.info("Blog to local file saved in %s, its url is %s" %(UPLOAD_FOLDER, imgUrl))
        #返回数据加上自定义头
        if editorType == "wangEditor":
            res = Response(imgUrl)
            res.headers["ContentType"] = "text/html"
        else:
            res = jsonify(url=imgUrl, message=None, success=1)
            res.headers["ContentType"] = "application/json"
    else:
        result = r"error|未成功获取文件或格式不允许，上传失败"
        if editorType == "wangEditor":
            res = Response(result)
            res.headers["ContentType"] = "text/html"
        else:
            res = jsonify(message=result, success=0)
            res.headers["ContentType"] = "application/json"
    res.headers["Charset"] = "utf-8"
    return res

#对头像图片上传进行响应
@upload_blueprint.route('/avatar/', methods=['POST','OPTIONS'])
def UploadAvatarImage():
    logger.sys.debug(request.files)
    f = request.files.get('file')
    # Check if the file is one of the allowed types/extensions
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_rnd_filename() + "." + f.filename.split('.')[-1]) #随机命名
        if PLUGINS['UpYunStorage']['enable'] in ('true', 'True', True):
            imgUrl = "/EauDouce/avatar/" + filename
            upres  = UploadImage2Upyun(imgUrl, f.stream.read())
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.sys.info("Avatar to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            if not os.path.exists(UPLOAD_FOLDER): os.makedirs(UPLOAD_FOLDER)
            f.save(os.path.join(UPLOAD_FOLDER, filename))
            imgUrl = "/" + IMAGE_FOLDER + filename
            logger.sys.info("Avatar to local file saved in %s, its url is %s" %(UPLOAD_FOLDER, imgUrl))
        # return user home and write avatar url into mysql db.
        res = g.api.user_update_avatar(g.username, imgUrl)
    else:
        res = {"success": False, "msg": u"上传失败: 未成功获取文件或格式不允许"}

    logger.sys.info(res)
    return jsonify(res)

#对封面图片上传进行响应
@upload_blueprint.route('/cover/', methods=['POST','OPTIONS'])
def UploadCoverImage():
    logger.sys.debug(request.files)
    f = request.files.get('file')
    # Check if the file is one of the allowed types/extensions
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_rnd_filename() + "." + f.filename.split('.')[-1]) #随机命名
        if PLUGINS['UpYunStorage']['enable'] in ('true', 'True', True):
            imgUrl = "/EauDouce/cover/" + filename
            upres  = UploadImage2Upyun(imgUrl, f.stream.read())
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.sys.info("Cover to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            if not os.path.exists(UPLOAD_FOLDER): os.makedirs(UPLOAD_FOLDER)
            f.save(os.path.join(UPLOAD_FOLDER, filename))
            imgUrl = "/" + IMAGE_FOLDER + filename
            logger.sys.info("Cover to local file saved in %s, its url is %s" %(UPLOAD_FOLDER, imgUrl))
        # return user home and write avatar url into mysql db.
        res = g.api.user_update_cover(g.username, imgUrl)
    else:
        res = {"success": False, "msg": u"上传失败: 未成功获取文件或格式不允许"}

    logger.sys.info(res)
    return jsonify(res)

#对头像图片裁剪后上传进行响应
@upload_blueprint.route('/clipper/', methods=['POST','OPTIONS'])
def UploadClipperAvatar():
    if request.form.get("action") == "add":
        data     = request.form.get("picStr")
        imgdata  = base64.b64decode(data)
        filename = gen_rnd_filename() + ".png" #随机命名
        if PLUGINS['UpYunStorage']['enable'] in ('true', 'True', True):
            imgUrl = "/EauDouce/avatar/" + filename
            upres  = UploadImage2Upyun(imgUrl, base64str(data))
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.sys.info("Avatar to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            if not os.path.exists(UPLOAD_FOLDER): os.makedirs(UPLOAD_FOLDER)
            file=open(os.path.join(UPLOAD_FOLDER, filename), 'wb')
            file.write(imgdata)
            file.close()
            imgUrl = "/" + IMAGE_FOLDER + filename
            logger.sys.info("Avatar to local file saved in %s, its url is %s" %(UPLOAD_FOLDER, imgUrl))
        # return user home and write avatar url into mysql db.
        res = g.api.user_update_avatar(g.username, imgUrl)
    else:
        res = {"success": False, "msg": u"不支持的action"}

    logger.sys.info(res)
    return jsonify(res)

@upload_blueprint.route('/test/', methods=['POST','OPTIONS'])
def test():
    logger.sys.debug(request.files)
    f = request.files.get('file')
    # Check if the file is one of the allowed types/extensions
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_rnd_filename() + "." + f.filename.split('.')[-1]) #随机命名
        if PLUGINS['UpYunStorage']['enable'] in ('true', 'True', True):
            imgUrl = "/EauDouce/test/" + filename
            upres  = UploadImage2Upyun(imgUrl, f.stream.read())
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.sys.info("TEST to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            if not os.path.exists(UPLOAD_FOLDER): os.makedirs(UPLOAD_FOLDER)
            f.save(os.path.join(UPLOAD_FOLDER, filename))
            imgUrl = "/" + IMAGE_FOLDER + filename
            logger.sys.info("TEST to local file saved in %s, its url is %s" %(UPLOAD_FOLDER, imgUrl))
        res = dict(code=0, imgUrl=imgUrl)
    else:
        res = {"code": -1, "msg": u"上传失败: 未成功获取文件或格式不允许"}

    logger.sys.info(res)
    return jsonify(res)

src/templates/front/blogIndex.html
{% extends "base/front.html" %}

{% block title %}首页{% endblock %}

{% block head %}
<style type="text/css">
    /*
    .carousel{
     background-color: #000000;
    }
    .carousel .item{
     max-height: 360px;
     background-color: #000000;
    }
    */
    .carousel img{
     height: 320px;
     //width: 100%;
    }
</style>
{% endblock %}

 {% block notice %}
            <marquee direction="left" scrollamount="5" bgcolor="#FFFFFF">
                {% for notice in g.api.get_sys_notice().data %}
                <i class="icon-bullhorn"></i>&nbsp;{{ notice.msg|safe }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {% endfor %}
            </marquee>
 {% endblock %}

{% block PathNavigation %}
			<ul class="breadcrumb">
				<li class="active">
					当前位置：<a href="{{ url_for('front.index') }}">首页</a>
				</li>
			</ul>
{% endblock %}

{% block AlternateDiagram %}
            {%- set banners = g.api.get_banner().data %}
            <div class="carousel slide" id="carousel-394119">
                <ol class="carousel-indicators">
                    {%- for banner in banners %}
                    <li data-slide-to="{{ loop.index0 }}" data-target="#carousel-394119"{% if banner.isActive %} class="active"{% endif %}></li>
                    {%- endfor %}
                </ol>
                <div class="carousel-inner">
                    {%- for banner in banners %}
                    <div class="item{% if banner.isActive %} active{% endif %}">
                        <a href="{{ url_for('front.blogShow', bid=banner.id) }}"><img src="{{ banner.imgUrl }}" width="1600px" height="320px"  /></a>
                        <div class="carousel-caption">
                            <p>{{ banner.title }}</p>
                        </div>
                    </div>
                    {%- endfor %}
                </div>
                <a class="left carousel-control" href="#carousel-394119" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-394119" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
{% endblock %}

{% block container %}
            <!-- 置顶文章列表 -->
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <h3>置顶文章</h3>
                    <ul class="list-unstyled">
                    {% for blog in g.api.blog_get_top_data().data %}
                        <li><a href="{{ url_for('front.blogShow', bid=blog.id) }}">{{ blog.title }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <!-- 文章列表缩略 -->
            {% set blogs = g.api.blog_get_single_index(page=request.args.get("page", 0), length=request.args.get("length", 8)) %}
            <h3>最新文章</h3>
            <blockquote>
            {% for blog in blogs.data %}
			<div class="row clearfix">
				<div class="col-md-12 column">
					<h4 class="text-left text-success">
						<a href="{{ url_for('front.blogShow', bid=blog.id) }}" style="color: blue; font-weight: bold;">{{ blog.title }}</a>
					</h4>
					<h5>
					    {% if blog.author %}
					    <small><i class="icon-user icon-1x"></i><a href="{{ url_for('front.userHome', user=blog.author) }}" title="由 {{ blog.author }} 发布" style="color: #999">&nbsp;{{ blog.author }}</a>&nbsp;</small>
					    {% endif %}

                        {% if blog.catalog %}
					    <small><i class="icon-folder-open icon-1x"></i><a href="{{ url_for('front.blogResource', resource_type='catalog', resource_data=blog.catalog) }}" title="查看 {{ blog.catalog }} 分类中所有文章" style="color: #999">&nbsp;{{ blog.catalog }}</a>&nbsp;</small>
					    {% endif %}

                        {% if blog.tag %}
					    <small><i class="icon-tag icon-1x"></i>
					    {% for tag in blog.tag.split() %}
					        <a href="{{ url_for('front.blogResource', resource_type='tag', resource_data=tag) }}" title="查看 {{ tag }} 标签中所有文章" style="color: #999">{{ tag }}</a>&nbsp;
					    {% endfor %}
					    </small>
					    {% endif %}

                        {% if blog.create_time %}
					    <small><i class="icon-calendar icon-1x"></i><scan style="color: #999">&nbsp;{{ blog.create_time }}</scan>&nbsp;</small>
					    {% endif %}

					    {%- if g.plugins.ChangyanComment.enable in ('true', 'True', True) %}
                        <small><i class="icon-comment-alt icon-1x"></i><a href="{{ url_for('front.blogShow', bid=blog.id) }}#SOHUCS" title="《{{ blog.title }}》 上的评论" style="color: #999">&nbsp;评论{{ g.api.misc_get_commend(blog.id).data.comments }}次</a>&nbsp;</small>
                        {% endif -%}
					</h5>
				</div>
			</div>
			{% endfor %}
			<!-- 分页 -->
			{%- set prev = blogs.page.page - 1 %}
			{%- set next = blogs.page.page + 1 %}
			{%- set last = blogs.page.PageCount - 1 %}
			<nav aria-label="">
            <center>
			<ul class="pagination">
			    {%- if blogs.page.page == 0 %}
				<li class="disabled"><a>Prev</a></li>
				{% else -%}
				<li><a href="{{ url_for('front.index', page=prev) }}">Prev</a></li>
				{% endif -%}
				{%- for p in range(blogs.page.PageCount) %}
				    {%- if blogs.page.page == p -%}
				        <li class="disabled"><a>{{ p }}</a></li>
				    {%- else -%}
				        <li><a href="{{ url_for('front.index', page=p) }}">{{ p }}</a></li>
				    {% endif -%}
                {% endfor -%}
			    {% if blogs.page.page == last %}
				<li class="disabled"><a>Next</a></li>
				{% else %}
				<li><a href="{{ url_for('front.index', page=next) }}">Next</a></li>
				{%- endif %}
			</ul>
			</center>
			</nav>
			</blockquote>
{% endblock %}


src/templates/front/blogResource.html
{% extends "base/front.html" %}

{% block title %}资源列表{% endblock %}

{% block PathNavigation %}
			<ul class="breadcrumb">
				<li>
					 <a href="{{ url_for('front.index') }}">首页</a>
				</li>
				<li>
					{% if request.args.get("resource_type") == "tag" %}
					标签
					{% elif request.args.get("resource_type") == "catalog" %}
					分类
					{% elif request.args.get("resource_type") == "sources" %}
					来源
					{% endif %}
				</li>
				<li class="active">
					{% if request.args.get("resource_data") == "1" %}
					    原创
					{% elif request.args.get("resource_data") == "2" %}
					    转载
					{% elif request.args.get("resource_data") == "3" %}
                        翻译
					{% else %}
					    {{ request.args.get("resource_data") }}
					{% endif %}
				</li>
			</ul>
{% endblock %}

{% block container %}
            <!-- 资源列表 -->
            {% if request.args.get("resource_type") == "catalog" %}
                {% set data = g.api.blog_get_catalog_data(request.args.get("resource_data")).data %}
            {% elif request.args.get("resource_type") == "sources" %}
                {% set data = g.api.blog_get_sources_data(request.args.get("resource_data")).data %}
            {% else %}
                {% set data = g.api.blog_get_tag_data(request.args.get("resource_data")).data %}
            {% endif %}
            {% for blog in data %}
            <blockquote>
			<div class="row clearfix">
				<div class="col-md-12 column">
					<h4 class="text-left text-success">
						<a href="{{ url_for('front.blogShow', bid=blog.id) }}" style="color: blue; font-weight: bold;">{{ blog.title }}</a>
					</h4>
					<h6>
					    {% if blog.author %}
					    <i class="icon-user icon-1x"></i><a href="{{ url_for('front.userHome', user=blog.author) }}" title="由 {{ blog.author }} 发布" style="color: #999">&nbsp;{{ blog.author }}</a>&nbsp;
					    {% endif %}

                        {% if blog.create_time %}
					    <i class="icon-calendar icon-1x"></i><scan style="color: #999">&nbsp;{{ blog.create_time }}</scan>&nbsp;
					    {% endif %}
					</h6>
				</div>
			</div>
			</blockquote>
			{% endfor %}
{% endblock %}

src/templates/front/userHome.html
{% extends "base/front.html" %}

{% block title %}用户{% endblock %}

{% block head %}
<style type="text/css">
.bg {
	display: table;
	width: 100%;
	height: 100%;
	padding: 50px 0;
	text-align: center;
	color: #fff !important;
	
	background-color: #000;
	background-size: cover;
}
fieldset{padding:.35em .625em .75em;margin:0 2px;border:1px solid #009;border-radius:5px;}
legend{padding:.5em;border:0;width:auto}

</style> 
{% endblock %}

{% block AlternateDiagram %}
    {% set data = g.api.user_get_one_profile(user).data %}
    <div class="bg" style="background: url({{ data.cover }}) no-repeat top center;">
		<div class="col-md-4 column">
		  	<a href="javascript:ShowAvatar('{{ data.avatar }}')"><img id="avatar" src="{{ data.avatar or 'https://img.saintic.com/EauDouce/avatar/default.jpg' }}" class="img-thumbnail" style="display: block; max-height: 200px" /></a>
		  	<p class="text-left text-default">
                <i class="icon-user icon-1x">&nbsp;</i><attr title="{{ data.motto or '' }}">{{ data.cname or data.username }}</attr><br/>

                {% if data.get('gender') == '男' %}
                    <i class="icon-time icon-1x">&nbsp;</i>A handsome boy Joined on {{ data.get('time') }}
                {% elif data.get('gender') == '女' %}
                    <i class="icon-time icon-1x">&nbsp;</i>A pretty girl Joined on {{ data.get('time') }}
                {% else %}
                    <i class="icon-time icon-1x">&nbsp;</i>Joined on {{ data.get('time') }}
                {% endif %}
                <br/>

                {% if data.get('url') %}
                    <i class="icon-link icon-1x">&nbsp;</i>我的网址: <a href="{% if 'http' in data.get('url') %}{{ data.get('url') }}{% else %}{{ 'http://' + data.get('url') }}{% endif %}" target="_blank">{{ data.get('url') }}</a><br/>
                {% endif %}

                {% if data.get('email') %}
                    <i class="icon-envelope icon-1x">&nbsp;</i>我的邮箱: <a href="mailto:{{ data.get('email') }}">{{ data.get('email') }}</a><br/>
                {% endif %}

                {% if data.get('weibo') %}
                    <i class="icon-twitter-sign icon-1x">&nbsp;</i>我的微博: <a href="{% if 'http' in data.get('weibo') %}{{ data.get('weibo') }}{% else %}{{ 'http://' + data.get('weibo') }}{% endif %}" target="_blank">{{ data.get('weibo') }}</a><br/>
                {% endif %}

                {% if data.get('github') %}
                    <i class="icon-github icon-1x">&nbsp;</i>我的代码: <a href="{% if 'http' in data.get('github') %}{{ data.get('github') }}{% else %}{{ 'http://' + data.get('github') }}{% endif %}" target="_blank">{{ data.get('github') }}</a><br/>
                {% endif %}

                <i class="icon-link icon-1x">&nbsp;</i>个性地址: {{ request.url_root.strip('/') + url_for('front.userHome', user=user)  }}<br/>
            </p>
		</div>
		<div class="col-md-4 column">
		</div>
        <div class="col-md-4 column">
            {% if g.signin and g.username == data.username %}
            <br><br><br><br>
            <fieldset>
                <a name="Setting"></a>
                <legend><small class="text-default text-lowercase">个人设置</small></legend>
                <div>
                    <a href="javascript:ChangerAvater()" class="btn btn-warning btn-lg btn-block active" role="button">修改头像</a>
                    <a href="javascript:ChangerPassword()" class="btn btn-danger btn-lg btn-block active" role="button">修改密码</a>
                    <a href="javascript:ChangerCover()" class="btn btn-success btn-lg btn-block active" role="button">修改封面</a>
                    <a href="javascript:ChangerProfile()" class="btn btn-info btn-lg btn-block active" role="button">修改个人资料</a>
                </div>
            </fieldset>
            {% endif %}
        </div>
    </div>
    <br/>
    <div>
        <a name="blog"></a>
		{% for blog in g.api.blog_get_user_blog(user).data %}
        <blockquote>
			<div class="row clearfix">
				<div class="col-md-12 column">
					<p class="text-left">
						<a href="{{ url_for('front.blogShow', bid=blog.id) }}" style="color: blue; font-weight: bold;">{{ blog.title }}</a>
					    <small><i class="icon-user icon-1x"></i><a href="{{ url_for('front.userHome', user=blog.author) }}" title="由 {{ blog.author }} 发布" style="color: #999">&nbsp;{{ blog.author }}</a>&nbsp;</small>
					    <small><i class="icon-calendar icon-1x"></i><scan style="color: #999">&nbsp;{{ blog.create_time }}</scan>&nbsp;</small>
					    {% if blog.tag %}
					    <small><i class="icon-tag icon-1x"></i>
					    {% for tag in blog.tag.split() %}
					        <a href="{{ url_for('front.blogResource', resource_type='tag', resource_data=tag) }}" title="查看 {{ tag }} 标签中所有文章" style="color: #999">{{ tag }}</a>&nbsp;
					    {% endfor %}
					    </small>
					    {% endif %}
					</p>
				</div>
			</div>
	    </blockquote>
		{% endfor %}
	</div>
{% endblock %}

{% block PathNavigation %}{% endblock %}

{% block notice %}{% endblock %}

{% block search %}{% endblock %}

{% block aside %}{% endblock %}

{% block container %}{% endblock %}

{% block script %}
<script type="text/javascript">
{% if g.username == user %}
// iframe层显示更改头像弹窗
function ChangerAvater() {
    layer.open({
        type: 2,
        title: '更换头像',
        shadeClose: true,
        shade: 0.8,
        area: ['900px', '660px'],
        content: '{{ url_for("front.userChangeAvater") }}'
    });
}

// iframe层显示更改密码弹窗
function ChangerPassword() {
    layer.open({
        type: 2,
        title: '修改密码',
        shadeClose: true,
        shade: 0.8,
        area: ['300px', '360px'],
        content: '{{ url_for("front.userChangePassword") }}'
    });
}

// iframe层显示更改封面弹窗
function ChangerCover() {
    layer.open({
        type: 2,
        title: '更换封面',
        shadeClose: true,
        shade: 0.8,
        area: ['300px', '260px'],
        content: '{{ url_for("front.userChangeCover") }}'
    });
}

// iframe层显示更改个人资料
function ChangerProfile() {
    layer.open({
        type: 2,
        title: '修改个人资料',
        shadeClose: true,
        shade: 0.8,
        area: ['70%', '90%'],
        content: '{{ url_for("front.userChangeProfile") }}'
    });
}
{% endif %}

//页面层-显示头像
function ShowAvatar(imgUrl) {
    var img = new Image();
    img.src=$("#avatar")[0].src;
    img.onload = function(){
        console.info("分析图片"+img.src+",宽为"+img.width+",高为"+img.height);
        layer.open({
            type: 1,
            title: false,
            closeBtn: 0,
            skin: 'layui-layer-nobg', //没有背景色
            shadeClose: true,
            area: [img.width, img.height],
            content: '<img src="' + imgUrl +'" />'
        });
    }
}
</script>
{% endblock %}