src/views/admin.py
# -*- coding: utf-8 -*-
"""
    EauDouce.views.admin
    ~~~~~~~~~~~~~~

    Managing background views.

    :copyright: (c) 2017 by Mr.tao.
    :license: MIT, see LICENSE for more details.
"""

from flask import Blueprint, g, render_template, request
from utils.tool import admin_login_required

admin_blueprint = Blueprint("admin", __name__)

@admin_blueprint.route("/")
@admin_login_required
def index():
    return render_template("admin/index.html")

@admin_blueprint.route("/profile/")
@admin_login_required
def profile():
    user = request.args.get("user")
    if user:
        return render_template("admin/profile.html", user=user)
    else:
        return ""

@admin_blueprint.route("/basic/blog/")
@admin_login_required
def basic_blog():
    return render_template("admin/basic/blog.html")

@admin_blueprint.route("/basic/user/")
@admin_login_required
def basic_user():
    return render_template("admin/basic/user.html")

@admin_blueprint.route("/basic/catalog/")
@admin_login_required
def basic_catalog():
    return render_template("admin/basic/catalog.html")

@admin_blueprint.route("/basic/commend/")
@admin_login_required
def basic_commend():
    return render_template("admin/basic/commend.html")

@admin_blueprint.route("/basic/project/")
@admin_login_required
def basic_project():
    return render_template("admin/basic/project.html")

@admin_blueprint.route("/basic/team/")
@admin_login_required
def basic_team():
    return render_template("admin/basic/team.html")

@admin_blueprint.route("/basic/filemanager/")
@admin_login_required
def basic_filemanager():
    return render_template("admin/basic/filemanager.html")

@admin_blueprint.route("/basic/plugin/")
@admin_login_required
def basic_plugin():
    return render_template("admin/basic/plugin.html")

@admin_blueprint.route("/system/configure/")
@admin_login_required
def system_config():
    return render_template("admin/system/configure.html")

@admin_blueprint.route("/system/notice/")
@admin_login_required
def system_notice():
    return render_template("admin/system/notice.html")

@admin_blueprint.route("/system/friendlink/")
@admin_login_required
def system_friendlink():
    return render_template("admin/system/friendlink.html")

@admin_blueprint.route("/system/clicklog/")
@admin_login_required
def system_clicklog():
    return render_template("admin/system/clicklog.html")

src/views/front.py
# -*- coding: utf-8 -*-
"""
    EauDouce.views.front
    ~~~~~~~~~~~~~~

    Foreground view.

    :copyright: (c) 2017 by Mr.tao.
    :license: MIT, see LICENSE for more details.
"""

import datetime
from urlparse import urljoin
from werkzeug.contrib.atom import AtomFeed
from flask import Blueprint, g, render_template, request, redirect, url_for, make_response, abort
from utils.tool import login_required, logger, BaiduActivePush

front_blueprint = Blueprint("front", __name__)

@front_blueprint.route("/")
def index():
    return render_template("front/blogIndex.html")

@front_blueprint.route('/blog/<int:bid>.html')
def blogShow(bid):
    data = g.api.blog_get_id(bid).get("data")
    if data:
        BaiduActivePushResult = False
        if g.plugins['BaiduActivePush']['enable'] in ("true", "True", True):
            BaiduActivePushResult = True if BaiduActivePush(request.url, original=True if data.get("sources") == "原创" else False).get("success_realtime") == 1 else False
        logger.sys.info("BaiduActivePushResult for id: %s, %s" %(bid, BaiduActivePushResult))
        return render_template("front/blogShow.html", blogId=bid, data=data, BaiduActivePushResult=BaiduActivePushResult)
    else:
        return abort(404)

@front_blueprint.route("/blog/write/")
@login_required
def blogWrite():
    return render_template("front/blogWrite.html")

@front_blueprint.route("/blog/edit/")
@login_required
def blogEdit():
    blogId = request.args.get("blogId")
    if blogId:
        data = g.api.blog_get_id(blogId).get("data")
        if data:
            if g.username == data.get("author") or g.username in g.api.user_get_admins().get("data"):
                return render_template("front/blogEdit.html", blogId=blogId, data=data)
        return abort(404)

@front_blueprint.route("/blog/resource/")
def blogResource():
    return render_template("front/blogResource.html")

@front_blueprint.route("/blog/search/")
def blogSearch():
    return render_template("front/blogSearch.html")

@front_blueprint.route("/user/<user>/")
def userHome(user=None):
    return render_template("front/userHome.html", user=user)

@front_blueprint.route("/user/ChangeAvater/")
@login_required
def userChangeAvater():
    return render_template("front/userChangeAvater2.html")
    return render_template("front/userChangeAvater.html")

@front_blueprint.route("/user/ChangePassword/")
@login_required
def userChangePassword():
    return render_template("front/userChangePassword.html")

@front_blueprint.route("/user/ChangeCover/")
@login_required
def userChangeCover():
    return render_template("front/userChangeCover.html")

@front_blueprint.route("/user/ChangeProfile/")
@login_required
def userChangeProfile():
    return render_template("front/userChangeProfile.html")

@front_blueprint.route("/robots.txt")
def robots():
    return """
User-agent: *
Disallow: 
    """

@front_blueprint.route("/sitemap.xml")
def sitemapxml():
    resp = make_response(render_template("public/sitemap.xml"))
    resp.headers["Content-Type"] = "application/xml"    
    return resp

@front_blueprint.route("/sitemap.html")
def sitemaphtml():
    return render_template("public/sitemap.html")

@front_blueprint.route("/feed/")
def feed():
    data = g.api.blog_get_all(limit=10).get("data")
    feed = AtomFeed(g.api.get_sys_config().get("data").get("site_feedname"), feed_url=request.url, url=request.url_root, subtitle="From the latest article in {}".format(request.url))
    for article in data:
        updated = article['update_time'][:10] if article['update_time'] else article['create_time'][:10]
        feed.add(article['title'], unicode(article['content']),
                 content_type='html',
                 author=article['author'],
                 id=article['id'],
                 url=urljoin(request.url_root, url_for(".blogShow", bid=article['id'])),
                 updated=datetime.datetime.strptime(updated, "%Y-%m-%d"),
                 published=datetime.datetime.strptime(article['create_time'][:10], "%Y-%m-%d"))
    return feed.get_response()

@front_blueprint.route("/thirds/StaticUpload/")
def thirdPluginStaticUpload():
    return render_template("admin/thirdPluginStaticUpload.html")

src/templates/base/admin.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <title>{% block title %}{% endblock %} | EauDouce - 后台管理</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <link href="/static/admin/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/static/admin/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/static/admin/css/animate.css" rel="stylesheet">
    <link href="/static/admin/css/style.css?v=4.1.0" rel="stylesheet">
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
    {% block head %}{% endblock %}
</head>

<body class="fixed-sidebar gray-bg">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i></div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">

                    <!--Logo or Title-->
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="{{ url_for('admin.index') }}">
                                <span class="clear">
                                    <span class="block m-t-xs" style="font-size:20px;">
                                        <strong class="font-bold">EauDouce&nbsp;Admin</strong>
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element">后台</div>
                    </li>

                    <!-- 导航大致分类 -->
                    <li>
                        <a class="J_menuItem" href="{{ url_for('admin.index') }}">
                            <i class="fa fa-dashboard"></i><span class="nav-label">仪表盘</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa fa-bar-chart-o"></i><span class="nav-label">统计图</span>
                        </a>
                    </li>

                    <!-- 基础管理分类 -->
                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">基础</span>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-linux"></i> <span class="nav-label">博客管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="{{ url_for('admin.basic_blog') }}">
                                    <i class="fa fa-book"></i> <span class="nav-label">文章管理</span>
                                </a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{{ url_for('admin.basic_user') }}">
                                    <i class="fa fa-user"></i> <span class="nav-label">用户管理</span>
                                </a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{{ url_for('admin.basic_catalog') }}">
                                    <i class="fa fa-folder-open"></i> <span class="nav-label">分类管理</span>
                                </a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="http://changyan.kuaizhan.com/overview" target="_blank">
                                    <i class="fa fa-commenting"></i> <span class="nav-label">评论管理</span>
                                </a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{{ url_for('admin.basic_project') }}">
                                    <i class="fa fa-github"></i> <span class="nav-label">开源项目管理</span>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.basic_team') }}">
                            <i class="fa fa-group"></i> <span class="nav-label">团队管理</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.basic_filemanager') }}">
                            <i class="fa fa-file-image-o"></i> <span class="nav-label">上传图片管理</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.basic_plugin') }}">
                            <i class="fa fa-puzzle-piece"></i> <span class="nav-label">插件配置管理</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.system_clicklog') }}">
                            <i class="fa fa-database"></i> <span class="nav-label">点击记录</span>
                        </a>
                    </li>

                    <!-- 系统管理分类 -->
                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">系统</span>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.system_config') }}">
                            <i class="fa fa-flask"></i> <span class="nav-label">系统配置</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.system_notice') }}">
                            <i class="fa fa-bullhorn"></i> <span class="nav-label">公告管理</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('admin.system_friendlink') }}">
                            <i class="fa fa-link"></i> <span class="nav-label">友情链接管理</span>
                        </a>
                    </li>

                    <!-- 左侧导航底部 -->
                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs"></li>
                    <li>
                        <center>
                            <i class="fa fa-child" style="font-size:20px;color:white"></i>&nbsp;<scan style="font-size:10px;color:green;">欢迎: <font size="2px">{{ g.username }}</font></scan>
                            <p class="text-muted credit" style="padding: 10px;">
                                &copy; 2017<br />
                                SaintIC, All rights reserved.
                            </p>
                        </center>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-info " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="请输入您需要查找的内容 …" class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li><a href="{{ url_for('front.index') }}" target="_blank"><i class="fa fa-home"></i>前台</a></li>
                        <!--消息导航-->
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i>消息&nbsp;&nbsp;<span class="label label-primary">8</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="mailbox.html">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> 您有16条未读消息
                                            <span class="pull-right text-muted small">4分钟前</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="profile.html">
                                        <div>
                                            <i class="fa fa-qq fa-fw"></i> 3条新回复
                                            <span class="pull-right text-muted small">12分钟钱</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a class="J_menuItem" href="notifications.html">
                                            <strong>查看所有 </strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                        <!--用户导航-->
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-user"></i><span>管理员</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><center><small>Signed in as <strong>{{ g.username }}</strong></small></center></li>
                                <li class="divider"></li>
                                <li><a href="#">我的资料</a></li>
                                <li><a href="{{ url_for('front.userHome', user=g.username) }}">我的主页</a></li>
                                <li><a href="{{ url_for('front.userHome', user=g.username) }}#blog">我的文章</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('front.userHome', user=g.username) }}#Setting" title="Setting">设置&nbsp;<i class="icon-cog icon-1x"></i></a></li>
                                <li><a href="{{ url_for('logout') }}" title="Sign Out">注销&nbsp;<i class="icon-signout icon-1x"></i></a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
            <!--<div class="row J_mainContent" id="content-main">
                <iframe id="J_iframe" width="100%" height="100%" src="index_v1.html?v=4.0" frameborder="0" data-id="index_v1.html" seamless></iframe>
            </div>-->
            <div class="wrapper wrapper-content">
                {% block content %}{% endblock %}
            </div>
        </div>
        <!--右侧部分结束-->
    </div>

    <!-- 全局js -->
    <script src="/static/admin/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/admin/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/static/admin/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/admin/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/static/layer/layer.js"></script>

    <!-- 自定义js:导航相关 -->
    <script src="/static/admin/js/hAdmin.js?v=4.1.0"></script>

    {% block script %}{% endblock %}

</body>

</html>

src/templates/base/admin_micro.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <link href="/static/admin/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/static/admin/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/static/admin/css/animate.css" rel="stylesheet">
    <link href="/static/admin/css/style.css?v=4.1.0" rel="stylesheet">
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
    {% block head %}{% endblock %}
</head>

<body>
    <div id="container">
        {% block content %}{% endblock %}
    </div>

    <!-- 全局js -->
    <script src="/static/admin/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/admin/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/static/admin/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/admin/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/static/layer/layer.js"></script>

    {% block script %}{% endblock %}
</body>
</html>

src/templates/base/front_micro.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{% block title %}{% endblock %} | {{ g.api.get_sys_config().data.site_title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="博客,blog,Interest,IT">
    <meta name="description" content="Linux,NoSQL,DevOps,python,Docker,redis,memcache,MongoDB,LVS,HA,LB,puppet,ansible,func,Cloud,BigData">
    <link rel="canonical" href="https://www.saintic.com/">
    <!-- 引入 Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- HTML5 Shim 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->
    <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
    {% block head %}{% endblock %}
</head>
<body>

<div class="container">

    <div class="header">
    <br />
    {% block container %}{% endblock %}
    </br>
    </br>
</div>

{% block Jquery %}<script src="{{ url_for('static', filename='js/jquery-3.1.0.min.js') }}"></script>{% endblock %}
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='layer/layer.js') }}"></script>
{% block script %}{% endblock %}
</body>
</html>